/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/works': typeof WorksRouteWithChildren
  '/works/$slug': typeof WorksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/works': typeof WorksRouteWithChildren
  '/works/$slug': typeof WorksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/works': typeof WorksRouteWithChildren
  '/works/$slug': typeof WorksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/works' | '/works/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/works' | '/works/$slug'
  id: '__root__' | '/' | '/works' | '/works/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorksRoute: typeof WorksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof WorksRoute
    }
  }
}

interface WorksRouteChildren {
  WorksSlugRoute: typeof WorksSlugRoute
}

const WorksRouteChildren: WorksRouteChildren = {
  WorksSlugRoute: WorksSlugRoute,
}

const WorksRouteWithChildren = WorksRoute._addFileChildren(WorksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorksRoute: WorksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
