/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as WorksSlugRouteImport } from './routes/works.$slug'
import { Route as ServicesUrbanDigitalTwinsRouteImport } from './routes/services.urban-digital-twins'
import { Route as ServicesScanToBimRouteImport } from './routes/services.scan-to-bim'
import { Route as ServicesPropertyVisualizationRouteImport } from './routes/services.property-visualization'
import { Route as ServicesImmersiveTrainingRouteImport } from './routes/services.immersive-training'
import { Route as ServicesHospitalityDigitalTwinsRouteImport } from './routes/services.hospitality-digital-twins'
import { Route as ServicesFacilitiesOperationsRouteImport } from './routes/services.facilities-operations'
import { Route as ServicesConstructionProgressRouteImport } from './routes/services.construction-progress'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as WorksCategoryCatRouteImport } from './routes/works.category.$cat'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSlugRoute = WorksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorksRoute,
} as any)
const ServicesUrbanDigitalTwinsRoute =
  ServicesUrbanDigitalTwinsRouteImport.update({
    id: '/services/urban-digital-twins',
    path: '/services/urban-digital-twins',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesScanToBimRoute = ServicesScanToBimRouteImport.update({
  id: '/services/scan-to-bim',
  path: '/services/scan-to-bim',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPropertyVisualizationRoute =
  ServicesPropertyVisualizationRouteImport.update({
    id: '/services/property-visualization',
    path: '/services/property-visualization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesImmersiveTrainingRoute =
  ServicesImmersiveTrainingRouteImport.update({
    id: '/services/immersive-training',
    path: '/services/immersive-training',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHospitalityDigitalTwinsRoute =
  ServicesHospitalityDigitalTwinsRouteImport.update({
    id: '/services/hospitality-digital-twins',
    path: '/services/hospitality-digital-twins',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFacilitiesOperationsRoute =
  ServicesFacilitiesOperationsRouteImport.update({
    id: '/services/facilities-operations',
    path: '/services/facilities-operations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesConstructionProgressRoute =
  ServicesConstructionProgressRouteImport.update({
    id: '/services/construction-progress',
    path: '/services/construction-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksCategoryCatRoute = WorksCategoryCatRouteImport.update({
  id: '/category/$cat',
  path: '/category/$cat',
  getParentRoute: () => WorksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/methodology': typeof MethodologyRoute
  '/works': typeof WorksRouteWithChildren
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/construction-progress': typeof ServicesConstructionProgressRoute
  '/services/facilities-operations': typeof ServicesFacilitiesOperationsRoute
  '/services/hospitality-digital-twins': typeof ServicesHospitalityDigitalTwinsRoute
  '/services/immersive-training': typeof ServicesImmersiveTrainingRoute
  '/services/property-visualization': typeof ServicesPropertyVisualizationRoute
  '/services/scan-to-bim': typeof ServicesScanToBimRoute
  '/services/urban-digital-twins': typeof ServicesUrbanDigitalTwinsRoute
  '/works/$slug': typeof WorksSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/works/': typeof WorksIndexRoute
  '/works/category/$cat': typeof WorksCategoryCatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/methodology': typeof MethodologyRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/construction-progress': typeof ServicesConstructionProgressRoute
  '/services/facilities-operations': typeof ServicesFacilitiesOperationsRoute
  '/services/hospitality-digital-twins': typeof ServicesHospitalityDigitalTwinsRoute
  '/services/immersive-training': typeof ServicesImmersiveTrainingRoute
  '/services/property-visualization': typeof ServicesPropertyVisualizationRoute
  '/services/scan-to-bim': typeof ServicesScanToBimRoute
  '/services/urban-digital-twins': typeof ServicesUrbanDigitalTwinsRoute
  '/works/$slug': typeof WorksSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/works': typeof WorksIndexRoute
  '/works/category/$cat': typeof WorksCategoryCatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/methodology': typeof MethodologyRoute
  '/works': typeof WorksRouteWithChildren
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/construction-progress': typeof ServicesConstructionProgressRoute
  '/services/facilities-operations': typeof ServicesFacilitiesOperationsRoute
  '/services/hospitality-digital-twins': typeof ServicesHospitalityDigitalTwinsRoute
  '/services/immersive-training': typeof ServicesImmersiveTrainingRoute
  '/services/property-visualization': typeof ServicesPropertyVisualizationRoute
  '/services/scan-to-bim': typeof ServicesScanToBimRoute
  '/services/urban-digital-twins': typeof ServicesUrbanDigitalTwinsRoute
  '/works/$slug': typeof WorksSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/works/': typeof WorksIndexRoute
  '/works/category/$cat': typeof WorksCategoryCatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/methodology'
    | '/works'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/services/construction-progress'
    | '/services/facilities-operations'
    | '/services/hospitality-digital-twins'
    | '/services/immersive-training'
    | '/services/property-visualization'
    | '/services/scan-to-bim'
    | '/services/urban-digital-twins'
    | '/works/$slug'
    | '/industries/'
    | '/insights/'
    | '/services/'
    | '/works/'
    | '/works/category/$cat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/methodology'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/services/construction-progress'
    | '/services/facilities-operations'
    | '/services/hospitality-digital-twins'
    | '/services/immersive-training'
    | '/services/property-visualization'
    | '/services/scan-to-bim'
    | '/services/urban-digital-twins'
    | '/works/$slug'
    | '/industries'
    | '/insights'
    | '/services'
    | '/works'
    | '/works/category/$cat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/methodology'
    | '/works'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/$slug'
    | '/services/construction-progress'
    | '/services/facilities-operations'
    | '/services/hospitality-digital-twins'
    | '/services/immersive-training'
    | '/services/property-visualization'
    | '/services/scan-to-bim'
    | '/services/urban-digital-twins'
    | '/works/$slug'
    | '/industries/'
    | '/insights/'
    | '/services/'
    | '/works/'
    | '/works/category/$cat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EstimateRoute: typeof EstimateRoute
  MethodologyRoute: typeof MethodologyRoute
  WorksRoute: typeof WorksRouteWithChildren
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesConstructionProgressRoute: typeof ServicesConstructionProgressRoute
  ServicesFacilitiesOperationsRoute: typeof ServicesFacilitiesOperationsRoute
  ServicesHospitalityDigitalTwinsRoute: typeof ServicesHospitalityDigitalTwinsRoute
  ServicesImmersiveTrainingRoute: typeof ServicesImmersiveTrainingRoute
  ServicesPropertyVisualizationRoute: typeof ServicesPropertyVisualizationRoute
  ServicesScanToBimRoute: typeof ServicesScanToBimRoute
  ServicesUrbanDigitalTwinsRoute: typeof ServicesUrbanDigitalTwinsRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof WorksRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$slug': {
      id: '/works/$slug'
      path: '/$slug'
      fullPath: '/works/$slug'
      preLoaderRoute: typeof WorksSlugRouteImport
      parentRoute: typeof WorksRoute
    }
    '/services/urban-digital-twins': {
      id: '/services/urban-digital-twins'
      path: '/services/urban-digital-twins'
      fullPath: '/services/urban-digital-twins'
      preLoaderRoute: typeof ServicesUrbanDigitalTwinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/scan-to-bim': {
      id: '/services/scan-to-bim'
      path: '/services/scan-to-bim'
      fullPath: '/services/scan-to-bim'
      preLoaderRoute: typeof ServicesScanToBimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/property-visualization': {
      id: '/services/property-visualization'
      path: '/services/property-visualization'
      fullPath: '/services/property-visualization'
      preLoaderRoute: typeof ServicesPropertyVisualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/immersive-training': {
      id: '/services/immersive-training'
      path: '/services/immersive-training'
      fullPath: '/services/immersive-training'
      preLoaderRoute: typeof ServicesImmersiveTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hospitality-digital-twins': {
      id: '/services/hospitality-digital-twins'
      path: '/services/hospitality-digital-twins'
      fullPath: '/services/hospitality-digital-twins'
      preLoaderRoute: typeof ServicesHospitalityDigitalTwinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/facilities-operations': {
      id: '/services/facilities-operations'
      path: '/services/facilities-operations'
      fullPath: '/services/facilities-operations'
      preLoaderRoute: typeof ServicesFacilitiesOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/construction-progress': {
      id: '/services/construction-progress'
      path: '/services/construction-progress'
      fullPath: '/services/construction-progress'
      preLoaderRoute: typeof ServicesConstructionProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/category/$cat': {
      id: '/works/category/$cat'
      path: '/category/$cat'
      fullPath: '/works/category/$cat'
      preLoaderRoute: typeof WorksCategoryCatRouteImport
      parentRoute: typeof WorksRoute
    }
  }
}

interface WorksRouteChildren {
  WorksSlugRoute: typeof WorksSlugRoute
  WorksIndexRoute: typeof WorksIndexRoute
  WorksCategoryCatRoute: typeof WorksCategoryCatRoute
}

const WorksRouteChildren: WorksRouteChildren = {
  WorksSlugRoute: WorksSlugRoute,
  WorksIndexRoute: WorksIndexRoute,
  WorksCategoryCatRoute: WorksCategoryCatRoute,
}

const WorksRouteWithChildren = WorksRoute._addFileChildren(WorksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EstimateRoute: EstimateRoute,
  MethodologyRoute: MethodologyRoute,
  WorksRoute: WorksRouteWithChildren,
  IndustriesSlugRoute: IndustriesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesConstructionProgressRoute: ServicesConstructionProgressRoute,
  ServicesFacilitiesOperationsRoute: ServicesFacilitiesOperationsRoute,
  ServicesHospitalityDigitalTwinsRoute: ServicesHospitalityDigitalTwinsRoute,
  ServicesImmersiveTrainingRoute: ServicesImmersiveTrainingRoute,
  ServicesPropertyVisualizationRoute: ServicesPropertyVisualizationRoute,
  ServicesScanToBimRoute: ServicesScanToBimRoute,
  ServicesUrbanDigitalTwinsRoute: ServicesUrbanDigitalTwinsRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
